_pages/githubstudent.json

This PR introduces `githubstudent` to the directory of pages. Please review @githubteacher!

Add githubstudent to page directory

---

_pages/carolynshin.yaml

This PR introduces @carolynshin to the directory of pages. 
Please review @githubteacher!

Introducing Carolyn's page to class repository

---

_pages/amit.yaml.txt

Just added my GitHub details as a part of the tutorials

Adding GitHub details

---

_pages/billyyumyum2x2.yaml

This pull request adds billyyumyum2x2's page to the class project! ✨

Adding billyyumyum page

---

_pages/rayjames.yaml

Well crap.  I created an earlier pull request but closed it when it came up with errors.  I don't think I should have done that.  Oh well, I'm learning though.  This is the new pull request with the correct indentation in the file.  Let's hope it's error free.

Rayjames add page

---

_pages/himyfairy.yaml

this pull request aims to add ‘himyfairy’ to the directory of pages, please review! @githubteacher , many thanks!

Add himyfairy to the page

---

_pages/jkrag.yaml

Added my page

---

_pages/JosephAncil.yaml

This is fantastic, and cool! learning something new every day makes me feel great. Thanks You!

Command line exploration

---

_pages/aronlindhagen.yaml

Aronlindhagen branch

---

_pages/VanceCarey.yaml

Adding my user page for the 102 tutorial

---

_pages/VanceCarey2.yaml

Adding the page I have but with cmd line

Adding my page(again)

---

_pages/milan08239.yaml

introducing milan08239 page

---

_pages/3xj.yaml

Add 3xj.yaml to _pages directory
\m/

Add 3xj page to repo

---

_pages/leiguoyang.yaml

I add my own page to this website. Feedback is welcome 😆

add leiguoyang.yaml

---

_pages/bjs007.yaml

bjs007.yaml added

---

_pages/Ji3m.yaml

Ji3m add page

---

_pages/Ji3m.yaml

One last time

---

_pages/Ji3m.yaml

Made a small modification to the file so as to allow a visible change.

Update the Ji3m.yaml file

---

_pages/ftheile.yaml

Added a page

---

_pages/carolynshin.yaml
_pages/himyfairy.yaml
_pages/rayjames.yaml
_pages/sorenDalsgaard.yaml

There were a few files showing up in the build failures so this PR fixes them!

Fixing misc syntax errors

---

_pages/john-waczak.yaml

"committing john-waczak.yaml to the github repo"

 commiting john-waczak.yaml to github repo

---

_pages/nelruk.yaml

This is my personal blog I wanna add. Review @githubteacher while I wait drinking coffee

Intro to my personal blog to class repository

---

_pages/john-waczak.yaml
_pages/nelruk.yaml

Please see diff for more info!

Fixing two build errors

---

_pages/jramirez0.yaml
mi_nombre.txt

Do you know my name?

---

_pages/jramirez0.yaml
_pages/m-meister.yaml
_pages/psywah.yaml

Now lets see if these changes will pass the CI test

Corrected some .yaml files

---

_pages/TsukiZombina.yaml

Add TsukiZombina page

---

_pages/gclaros.yaml

Add gclaros favourite web site

Add gclaros page

---

_pages/abenitez.yaml

This PR introduces to the directory of page. Please review @githubteacher, @gclaros

Introducing githubstudent's page to class repository

---

_pages/songye.yaml

this pr 
‘songye’ to the directory 
please review @githubteacher

Add songye to page directory

---

_pages/john-nascimento.yaml

Let's check if it's working properly

Trying to pass through CI test

---

_pages/ZenHatesCoding.yaml

ZP add pages

---

_pages/ONightPerson.yaml

@githubteacher what do you think?

add my pages

---

_pages/manu-garrido.yaml

Adding my page

---

_pages/bigablecat.yaml

create a .yaml file

---

_pages/arturparkhisenko.yaml

Please review @githubteacher !

Add arturparkhisenko to page directory

---

_pages/jwelham.yaml

github info

---

bhbai.yaml

add my yaml file

---

_pages/michaellnguyenn.yaml

This PR introduces "michaellnguyenn" to the directory of pages. Please review @githubteacher !

Add michaellnguyenn to page directory

---

_pages/raywail.yaml

This PR introduces "raywail" to the directory of pages. Please review @githubteacher!

Add raywail to page directory

---

_pages/n0madcat.yaml

Add no--cat page

---

_pages/MauritsFoobar.yaml

Add MauritsFoobar.yaml to _pages

Add MauritsFoobar.yaml

---

_pages/fongj2.yaml

This PR introduces 'fongj2' to the directory of pages. Please review @githubteacher!

Adding fongj2's to page

---

_pages/ijmarquez.yaml

This PR introduces ‘ijmarquez’ to the directory of pages. Please review @githubteacher!

Add ijmarquez to page directory

---

_pages/catherinetran1.yaml

This PR introduces ‘catherinetran1’ to the directory of pages. Please review @githubteacher

adding catherinetran1 to page directory

---

_pages/chengj9.yaml

This introduces chengj9 to the directory of pages. review @githubteacher

chengj9's page to class directory

---

_pages/colleen0605.yaml

This PR introduces ‘colleen0605’ to the directory of pages. Please review @githubteacher!

Introducing colleen0605's page to class repository

---

_pages/jonathankumamoto.yaml

added my file

---

_pages/aar1995.yaml

aar1995 url page

---

_pages/jun-xue.yaml

This pull request closes #181.

Introducing webpage to class repository

---

_pages/username.yaml

Introduces to page directory. Please review @githubteacher!

add githib student to directory

---

_pages/jtrevizo.yaml

adding jtrevizo page

---

_pages/andreasferox.yaml

This PR introduces 'andreasferox' to page directory. Please review @githubteacher

Add andreasferox to page directory

---

_pages/ypossem.yaml

This is for the zen process of I NEED TO MERGE. PLEASE MY ENTIRE SELF WORTH IS BASED ON MY CAPACITY TO MERGE. No, I lie. By the way I used 'date --iso-8601=ns' for my timestamp

adding my tag to this wall with git command line

---

_pages/eicholz.yaml

Adding eicholz to class

---

_pages/SaurabhSinghHcl.yaml

make username yaml file

---

_pages/krasnov8953.yaml

Add krasnov8953.yaml

---

_pages/samadmoizc8.yaml

This PR introducess `samadmoizc8` to the directory of pages. Please review @githubteacher

Add samadmoizc8 to page directory

---

_pages/kervince.yaml

I am trying to get the task completed.

I updated my website with today's date.

---

_pages/babay2.yaml

add file babay2.yaml

---

_pages/jameshuang304.yaml

add new page

---

_pages/VanceCarey2.yaml
_pages/damooch.yaml

Damooch add page

---

_pages/dmarchetti.yaml

Adding a page with my information and today's date.

Adding page

---

_pages/ahlweb.yaml

added name site and timestamp

---

_pages/blake1991.yaml

Please add my yaml file to the master branch.

Adding my own webpage

---

_pages/dmarchetti.yaml

Changing time stamp and url address.

---

_pages/jeremyjohnson7.yaml

Added file

---

_pages/vyablonskyy.yaml

This PR introduces vyablonskyy’s page to the directory of pages. Please review @githubteacher

Add vyablonskyy to page dirctory

---

_pages/dirkstagger.yaml

add dirkstagger.yaml under _pages dir

add dirkstagger

---

_pages/bgchpmn.yaml

This PR introduces 'bgchpmn' to the directory of pages. Please review @githubteacher.

Add bgchpmn to page directory.

---

_pages/dirkstagger.yaml

modify dirk stagger - sweetwifeBday

---

_pages/mcGIT123.yaml
_pages/mcGIT123.yaml.txt

commit to githubclassroom

---

_pages/JulianGarzon509.yaml

This PR introduces 'JulianGarzon509' to the directory of pages. Please review @githubteacher!

Add JulianGarzon509 to page directory

---

_pages/johncooperpdx.yaml

Reverts githubschool/on-demand-github-pages#478

Revert "Add johncooperpdx to page directory"

---

_pages/ZenHatesCoding.yaml
_pages/bdoenges.yaml

Here is the bdoenges pages file

Create bdoenges pages file

---

Mentoronto.yam1
_pages/Mentoronto.yaml
_pages/flinze.yaml

github page url

---

_pages/acisneros.yaml

Adding a page for acisneros

---

_pages/ReiB.yaml

Just adding some info to the Master.

Adding my Info

---

_pages/dareno.yaml

added dareno page

---

_pages/ljmwaugh.yaml

added ljmwaugh.yaml

---

_pages/aqkfatmtvvfb.yaml

aqkfatmtvvfb.github.io/learn_github/

aqkfatmtvvfb-add-page

---

_pages/pogorek.yaml

This PR introduces 'pogorek' to the directory of pages. Please review @githubteacher .

Introducing pogorek's page to class repository

---

_pages/susanli2016.yaml

This PR introduces 'susanli2016' to the directory of pages. Please review @githubteacher!

Add susanli2016 to page directory

---

_pages/pataytayojen.yaml

This PR introduces 'pataytayojen' to the directory of pages. Please review @githubteacher

Add pataytayojen to page directory

---

_pages/freemacj.yaml

attempt #2 to add freemacj.yaml

adding freemacj.yaml

---

_pages/themooselet.yaml

Adding my .yaml, now corrected.

Themooselet add page

---

_pages/borzumate.yaml
_pages/cgb7uu.yaml
_pages/cpchengit.yaml
_pages/damooch.yaml
_pages/lloydouyang.yaml
_pages/neverlosemypassion.yaml
_pages/orlandosalas.yaml
_pages/sathyacse67.yaml
_pages/themooselet.yaml

Just cleaning up some linter warnings. Will go ahead and :ship: as soon as the tests pass.

Clean up linter warnings

---

_pages/benweishi.yaml

Add my page

---

_pages/sushchikh.yaml

Sushchikh another page

---

_pages/jmatthewlandis.yaml
_pages/sushchikh.yaml

add a yaml file with my github info

add personal yaml file

---

_pages/eugelogic.yaml

Add Eugelogic's page to the showcase :-)

Add Eugelogic's page to the showcase

---

_pages/kvwalker.yaml

Add kvwalker page

---

_pages/derechoandrea.yaml

This new PR introduces my new page to the directory, Please @githubteacher review it!

Add derechoandrea new page to the directory

---

_pages/shutsen.yaml

Please add my changes to the master branch

---

_pages/davidjgithubtraining.yaml

This PR introduces 'davidjgithubtraining' to the directory of pages.  Please review @githubteacher.

Add davidjgithubtraining's page to class repository

---

_pages/ridsjin.yaml

Just a small PR to fix a single linter warning. Will merge as soon as the tests pass.

Fixing up linter errors

---

_pages/GIIRRII.yaml
_pages/GIIRRII.yml

Just a learning exercise t operate on.

commit home page link for my webapge

---

_pages/kriskirov.yaml
_pages/pogorek.yaml

CI fails because of this. User must have deleted his/her website

Delete missing websites

---

_pages/arnaudkleinveld.yaml

Create a page as explained by GH school

Please add my page

---

_pages/stormrider41.yaml

added page again

---

_pages/dagniel.yaml

Request to add page

---

_pages/dagniel_103.yaml

Pull request for @dagniel with #886

page for the 103 tutorial

---

_pages/AliEsmaeili.yaml

@githubteacher  Would you please take a look?

Add AliEsmaeili page

---

_pages/dawithw.yaml

Change to the right pageURL
dawithw.github.io

Fix dawithw.yaml file

---

_pages/elacai.yaml

Use Github Desktop to send pull request

ElaCai add page

---

_pages/mbryant1988.yaml

my ##github handle##
##pageurl##
and ##timestamp##

yaml file created with handle pageurl and timestamp

---

_pages/luoshao23.yaml

add luoshao23.yaml

---

_pages/willxiao90.yaml

willxiao90.github.io 404 not found

Willxiao90 add page

---

_pages/dan-i-am.yaml

Added change

---

_pages/rmachuca89.yaml

Adds my personal repo github page to this awesome collaborative and pragmatic github-school one.

Adds rmachuca89.yaml github.io page

---

_pages/cstone001.yaml

Add my page to the _pages directory

Add cstone001.yaml

---

_pages/13mtfb.yaml
_pages/mbryant1988.yaml
_pages/rmondragon1987.yaml

created rmondragon1987.yaml file as requested by project.

add rmondragon1987.yaml

---

_pages/zomilo.yaml

Prvi pokusaj

---

_pages/githubteachera.yaml

Add githubstudentpage

---

_pages/paulero.yaml

Paulero add page

---

_pages/wb2ifs.yaml

this introduces my page to the directory of pages

add wb2ifs page to class repo

---

_pages/efoxweb.yaml
_pages/nickhericks.yaml

Add nickhericks

---

_pages/panic-stricken.yaml

Page seems to have been added successfully.
Guided Tour: @githubteacher 
Student: @panic-stricken
closes #1056

Page added

---

_pages/qservando.yaml

Initial commit to site

---

_pages/btaylor19892.yaml
_pages/masaru-ryumae.yaml

intro addition

---

_pages/badcoder28.yaml

Add badcoder28

---

_pages/anule.yaml

I am adding my github pages site to this public directory.

add github pages site.

---

_pages 2
_pages/EllenaWarrantGroup.yaml
_pages/PatyGilbon.yaml

Add PatyGilbon

---

_pages/gavilan.yaml
_pages/mcGIT123.yaml

add page for user gavilan

---

_pages/shiftout.yaml

Fixing linter issues to clean up tests.

Linter fix

---

_pages/kyleweishaar.yaml
_pages/nelruk.yaml

This PR should allow the tests to continue to build.

Delete broken page

---

_pages/iadams7.yaml

iadams7 add page

---

_pages/JYang.yaml

What do you think? @githubteacher

Add JYang's Page

---

_pages/hugoram.yaml

Add my user page.

---

_pages/castrosalazr.yaml
_pages/jenlscribner.yaml

@githubteacher @brianamarie Hi Briana, I have updated my .yaml to point the URL to where it looks like my site is actually published:  https://jenlscribner.github.io/web-jls/ 
Hopefully, this helps.  Thanks!

Jenlscribner add page - 2nd try

---

_pages/algusdark.yaml

Add cool data from AlgusDark

---

_pages/hernanrenteria.yaml

screwing this up

---

_pages/mashysha.yaml

@githubteacher what do you think?

Add Mashysha's page

---

_pages/maboud.yaml

add my _page

---

_pages/skeoke.yaml

skeoke add page

---

_pages/youngdad33.yaml

Follow the Github desktop lesson, add my details to the repo _pages

Add my details

---

_pages/nhayato.yaml

Add nhayato page

---

_pages/richardz1011.yaml

add personal page

---

_pages/richardz1011.yaml

fifth time

---

_pages/paulo-raoni.yaml

First change as a begginer ;)

---

_pages/naythiha.yaml

Add naythiha page

---

_pages/naythiha.yaml

Add naythiha project site

---

_pages/danny666phantom.yaml
_pages/jquiro12.yaml
_pages/naythiha.yaml
_pages/paulo-raoni.yaml

Danny666phantom add page

---

_pages/vinar.yaml
_pages/vinar2.yaml

Adding vinar.yaml

---

_pages/VictorArias24.yaml
_pages/cwanjohi.yaml

what do you think @VictorArias24?

VictorArias24 add page

---

_pages/LevaMerzlyak_2.yaml

Add LevaMerzlyak's page!

---

_pages/mbrasseau.yaml

add webpage info

---

_pages/GregJablonski.yaml

Adding my page - @githubteacher please check
Closes #1334

Add GregJablonski page

---

_pages/biotemon.yaml

Add biotemon page

---

_pages/rheinze.yaml

Add rheinze page

---

_pages/yang.yaml

@githubteacher  What do you think?

Add-github student page

---

_pages/felladin.yaml

Adding yaml-file for Felladin.

---

_pages/anlexN.yaml

add anlexN.yaml to this repo

---

.github/teacherbot.yml

@hectorsector @beardofedu would you mind taking a look at this one too?

Add custom messages for teacherbot

---

.github/teacherbot.yml

This PR customizes Teacherbot's responses when a user closes a PR with or without merging.

Add merged and unmerged responses

---

_pages/cazsol.yaml
_pages/eutherio.yaml
_pages/jantonioavalos.yaml
_pages/paulero.yaml

Cazsol page-commit

---

.github/teacherbot.yml
_pages/ReiB.yaml
_pages/RhuanKrum.yaml
_pages/dan-i-am.yaml
_pages/socsuc.yaml

This pull request updates teacherbot's configs so that teacherbot points to the correct invitation. Thank you @crichID for helping me find this bug 😄

Update teacherbot config to point to correct invitations url

---

_pages/tchell.yaml

Adding my page to the course repo

---

_pages/PaulNorthPole.yaml
_pages/VictorArias24.yaml
_pages/gedsaro.yaml

had to remove a link that did not work, hopefully that is all

Gedsaro add page

---

_pages/tobbe-j.yaml

Tobbe j add page

---

_pages/ccianos.yaml
_pages/m1guelpf.yaml
_pages/zian999.yaml

Adding my personal page to the showcase.

Added personal page

---

_pages/m1guelpf.yaml
_pages/mjgarpe.yaml
_pages/zian999.yaml

Add mjgarpe page

---

_pages/dohai90.yaml

Adding dohai90 page

---

_pages/marshallhahn.yaml

I am adding my site to the class

Adding my site

---

_pages/rafaelsiza.yaml

what you think, @githubteacher ?

Creating a profile site

---

_pages/joanmarmu.yaml

add page yaml joanmarmu

---

_pages/KhanhDangDuy.yaml

Creating site for KhanhDangDuy.

Add file according to GitHub training

---

_pages/sosiology.yaml

added page with handle, url and time stamp

added page

---

_pages/bas.yaml

Added bas pages site

---

_pages/PandaBearz.yaml

Samuel VanCuren Added PandaBearz.yaml

Add _pages/PandaBearz.yaml With Github Information

---

_pages/eaamaral1.yaml

Added githubHandle, PageUrl, and timestamp.

Added eaamaral1

---

_pages/JustinHartline.yaml

This is a pull request to complete GitHub On-Demand Training 102.

Adding JustinHartline's page

---

_pages/andres-gu.yaml

andres-gu add page

---

_pages/Kuroi-Gengetsu.yaml
_pages/Telmoco.yaml
_pages/alonzocarlos.yaml

Noticed a few linter errors hanging out  in the CI results. This PR will clean those up (and any others I find).
Will merge once everything is passing.

Linter error clean up

---

_pages/papadavis47.yaml

Working with GitHub Desktop Tutorial

Adding to On Demand

---

_pages/kuzha.yaml

Add kuzha page

---

_pages/kuzha.yaml

Reverts githubschool/on-demand-github-pages#1791

Revert "Add kuzha page"

---

_pages/primerabbit.yaml

What do you think? @githubteacher

Add primerabbit's file

---

_pages/SeanOMealia.yaml

Add Sean O'Mealia site

---

_pages/mvmatrosov.yaml

Yaml file added

---

_pages/allancytan.yaml

add-allancytan-page

---

_pages/moto2600.yaml

Add Moto2600 File

---

_pages/Aotoge.yaml
_pages/SMAK1993.yaml
_pages/moto2600.yaml
_pages/seanrocky.yaml
_pages/tkosaber.yaml
_pages/vagacoder.yaml

Add Aotoge's details

---

_pages/mcoumounduros.yaml

What do you think @githubteacher

Add GitHandle into the project

---

_pages/george-becker.yaml

https://github.com/githubschool/on-demand-github-pages.git

---

_pages/nileshkumar.yaml

Added content for the new branch

add file for nuleshkumar

---

_pages/eduardo06sp.yaml

Eduardo06sp add page

---

_pages/carolina-lp.yaml

adding carolina-lp page

---

_pages/ferrerpaolo.yaml

2nd exercise commit via gitbash

update for next exercise

---

_pages/johnnyl72.yaml

added johnnyl72

---

_pages/fenmir.yaml

fenmir-add-page

---

_pages/AmirMokhtare.yaml

What do you think? 
Can we proceed forward?

push to access

---

_pages/JAQB689.yaml
_pages/JAQB689.yaml.txt

Add JAQB689 file

---

_pages/weizhi-luo.yaml

@githubteacher, add weizhi-luo page. 
The request closes #1990

Add weizhi-luo page

---

_pages/wjen.yaml
wjen.yaml

add page, moved to pages directory

Wjen add page

---

_pages/Julianchan801.yaml

Julianchan801 add page

---

_pages/kenji-nakayu.yaml

I am adding my personal website as part of the course tutorial.

Submitting my personal website

---

_pages/scamanda.yaml

Created scamanda.yaml file in _pages and edited text per tutorial

added scamanda.yaml to _pages

---

_pages/AlexSteele79.yaml

Added my page!

---

_pages/Svalab.yaml

Adding my yaml page

---

_pages/Kayakin2.yaml

Add file Kayakin2.yaml

---

_pages/alexisdemeo.yaml

Add new page final

---

_pages/LarryZam.yaml

What do you think? @githubteacher

larryzam-add-page

---

_pages/iSirThijs.yaml

Added my page :D

---

_pages/username.yaml

Added a file "username.yaml" with my info

Added file username.yaml with my info

---

_pages/jessiegouw.yaml

Added github name, link and my current timestamp

Adding jessiegouw.yaml to master

---

_pages/username.yaml

I forgot to give the file the right name :man_facepalming:
Fixed it, I hope 🙏

Added file to _pages named "jesseDijkman1.yaml"

---

_pages/marijnone.yaml

Marijnone add page

---

_pages/fjvdpol.yaml

Added fjvdpol.yaml file
closes #2201

Added fjvdpol.yaml

---

_pages/tomoversluizen.yaml

Added a new file

---

_pages/patrickvdveldt.yaml

Naam en datum toegevoegd

---

_pages/Rowin206.yaml
_pages/silver-surfer94.yaml

Added githubhandle info

---

_pages/SoulaimaneEC.yaml

Name, date etc

---

_pages/superstephan1.yaml

fixed typo, fixed date, added superstephan1 page

Superstephan1 add page

---

_pages/BasPieren.yaml

Added webpage to master
This pull request closes #2246

Added BasPieren.yaml

---

_pages/taruma.yaml

Add taruma's page

---

_pages/rbntimes.yaml

Add myself

---

_pages/chelseadoeleman.yaml

Add page chelseadoeleman

---

_pages/jessiemasonx.yaml

jessiemasonx.yaml toegevoegd

---

_pages/jeroentvb.yaml

added my github pages info
closes #2170

Jeroentvb add page

---

_pages/sterrevangeest.yaml

Added my githubpage tot sterrevangeest.yaml

add sterrevangeest.yaml

---

_pages/ninavanbergen.yaml

ninavanbergen toegevoegd

---

_pages/slodderwolf.yaml

Hi everyone 👋 , they skip a step in the course. Dont forget to make an issue with "request push acces"

add yaml file

---

_pages/Techdemo.yaml

Secondbranch

---

_pages/gijslaarman.yaml

added the page of gijslaarman

---

_pages/mishamje.yaml

Add the file mishamje.yaml to _pages directory.

Add mishamje.yaml

---

_pages/lauraesmee.yaml

here are the first set of changes

added lauraesmee.yaml

---

_pages/Dutchsilab.yaml

My new website
@githubteacher Whatcha think?

Dutchsilab

---

_pages/rme.yaml

Test from rme

---

_pages/mfazz.yaml

adding my file

---

_pages/alamfard.yaml
_pages/rme.yaml

@githubteacher check this branch ;)
and close #2346 .

Add Alamfard's files

---

_pages/Root-ish.yaml

Added Root-ish

---

_pages/SamuilDarik.yaml
_pages/maikxx.yaml
_pages/rarity2018.yaml

Add a page

---

_pages/username.yaml

What do you thing @githubteacher?

Add admntio page

---

_pages/sandoronodi.yaml

add content

---

_pages/martinsatt.yaml

Adding martinsatt

---

_pages/mryoho.yaml
_pages/samanthabaita.yaml

Add mryoho to project

---

_pages/JenPatchett.yaml

Add JenPatchett's file

---

_pages/yershovaleksandr.yaml

add my staff

---

_pages/karrypro.yaml
_pages/rikku-pp.yaml

A minimal page add. 
The page url looks abnormal, but it's the only valid url I have!

add rikku-pp user page as .yaml

---

_pages/bobbycupp.yaml

personal details

---

_pages/jakedw.yaml
_pages/rsboudreaux.yaml

Add GitHub handle, page URL and timestamp

Add username page

---

_pages/emil-monchev.yaml

Add my training home page to shared repo.

Add my training home page to shared repo.

---

_pages/maju3632.yaml

my new file

---

_pages/frisupforeve.yaml
_pages/rowhar.yaml

Adding a file in _pages with my information.

Adding a file with my info

---

_pages/lihaa.yaml

add lihaa page

---

_pages/iliana-p.yaml

Added my page. Will this work?

Add iliana-p file

---

_pages/richardson3535.yaml

Add richardson3535's page

---

_pages/andgate.yaml

Add my page to this junk repo

---

_pages/ThaoThanhLuu.yaml

here are the changes made with cmd

---

MattSHarker.yaml
_pages/andgate.yaml
_pages/mattsharker.yaml

This adds the MattSHarker.yaml file

Adding MattSHarker.yaml

---

_pages/nsuzue.yaml

Please add my file to the repository.

Add nsuzue's file

---

_pages/cordeliaroberts.yaml

added page for user cordeliaroberts

---

_pages/highdefsquirrelgirl.yaml

high def squirrel girl added her project to the file

added my project

---

_pages/Vonylla.yaml

Add Vonylla

---

_pages/smithmich12.yaml

Add Page smithmich12

---

_pages/Andrewid.yaml

I am a student at # Weber State University 
Taking # CS 3050 - Enterprise Computing

Andrew Quinn Merrell added his page

---

_pages/username.yaml

woah an added page so good

---

_pages/devNorthWest.yaml

Added a timestamp, my githubHandle, and my page URL.

Created .yaml file

---

_pages/yashNadun.yaml

adding yashNadun.yaml

---

_pages/Wi1he1m.yaml

maybe I need to change the repo name... we shall see

Add webpage

---

_pages/andrejkurusiov.yaml

how about this, @githubteacher ?

add own page stamped with date

---

_pages/codesaurusrex.yaml
_pages/wjen.yaml

Created a .yaml file within _pages to add my details to the repository.

Added my own page to folder

---

_pages/awister.yaml

Changes to be committed:
new file: awister.yaml

add awister index page

---

_pages/annasvst.yaml

Adding annasvst.yaml page to the project

Adding annasvst.yaml

---

_pages/robertshugart.yaml

Add RobertShugart File

---

_pages/unoabraham.yaml

Adding my details to on demand Github Pages.

Adding Details On Demand Github Pages

---

_pages/appintos.yaml
_pages/wjen.yaml

Changes to be committed:
new file:   appintos.yaml

 On branch appintos-add-page

---

_pages/dunn-cwu.yaml
_pages/lizurdlunker.yaml

updated the date to correspond to the cli tutorial date

updated the date

---

_pages/t-swan.yaml
_pages/tonezz.yaml

Added my username page

---

_pages/rdkeijzeror.yaml

Added page for rdkeijzeror

---

_pages/highdefsquirrelgirl.yaml
_pages/jjazz47.yaml

-add my own yaml file.
-remove highdefsquirrelgirl yaml file to fix build failure

Jjazz47 add page

---

_pages/jjazz47.yaml

-Finished the tutorial course. Remove my page file so it won't
break master in the future.
-This is a good course. Good job github!

issue:https://github.com/githubschool/on-demand-github-pages/issues/2988

---

_pages/BlessedChild.yaml

What do u think @BlessedChild?

add BlessedChild's file

---

_pages/jswett77.yaml

Ok, needed to accept the request first, doh!

ugh, one more time for jswett77

---

_pages/T-WEN.yaml

What do u think @T-Wen.github.io?

add T-WEN's page

---

_pages/1dhiman.yaml
_pages/williamthio.yaml

This pull request closes #2902.

Add williamthio.yaml

---

_pages/chinsloo.yaml

Added chinsloo page.

---

_pages/jrfv.yaml

My inital commit at yaml file index

My inital commit at yaml file index

---

_pages/jrfv.yaml

Commit changes in yaml index

---

_pages/eketiger.yaml

What do you think about this **awesome** *webpage*?
;)

Agregar página

---

_pages/jrfv.yaml

Initialize changes on yaml file

Initialize changes on yaml file

---

_pages/chinsloo.yaml

to solve a merge conflict on PR #2960

remove a new line

---

_pages/1dhiman.yaml
_pages/kjonathante.yaml

add kjonathante.yaml

---

_pages/beepbeepribbyribby.yaml

Addition of beepbeepribbyribby yaml
Fixes: #3095

beepbeepribbyribby yaml file

---

_pages/groiq.yaml

Adding page for user groiq to showcase

adding page for groiq

---

_pages/ting11222001.yaml

Add ting11222001.yaml 's file: Issues #3119

---

_pages/TimperatorTW.yaml

A page is added

---

_pages/simbadeveloper.yaml

add my page on-demand

---

_pages/kjbayliss.yaml

i'm adding this because the tutorial says to!

go tutorial dude

---

_pages/Olbs.yaml
_pages/alanofbrent.yaml
_pages/bradleydavidnelson.yaml
_pages/bradleydavidnelson.yaml.txt
_pages/groiq.yaml

@githubteacher Why am I failing the continuous integration checks?

Add bradleydavidnelson.yaml file

---

_pages/thealienthing.yaml

thealienthing.yaml added | pull request

---

_pages/ledihildawan.yaml
_pages/lonesome-data.yaml

@githubteacher please add lonesome-data.yaml to master

add lonesome-data.yaml to _pages

---

_pages/raini35.yaml

Add raini35 page to pages directory

---

_pages/nmegrant.yaml

Add to pages

---

_pages/Salcon77.yaml

Adding my handle
This closes issue #3455.

Salcon77 add page

---

_pages/tfranciscoj.yaml

Working on the tutorial about the command line. Add my webpage to the repository of class.

adding my webpage to repository

---

_pages/_pnan.yaml
_pages/franky-codes.yaml
_pages/miketide08.yaml

Pnan add page

---

_pages/qasimmohammed.yaml

Add my github website page, but this message has *more* detail

Add my github website page

---

_pages/qasimmohammed.yaml

changing the date as I already done some part of this with the gui

---

_pages/shuyaoli.yaml

Add shuyaoli.yaml

---

_pages/ross-u.yaml

Add ross-u.yaml file to the _pages/ dir

---

_pages/NorgaardA.yaml
_pages/remccormick.yaml

Remccormick add page - corrected yaml

Remccormick add page - corrected yaml

---

_pages/GiuseppeBaldini.yaml

Adding my (almost empty) page.

Add Giuseppe Baldini's page

---

_pages/jameszenartist.yaml

Jameszenartist add page

---

_pages/ChaseMatzinger.yaml
_pages/anddriex.yaml
_pages/jameszenartist.yaml

adding a web page

---

_pages/lujiejie636625.yaml

what do you think @githubrobot

github lujiejie636625's file add

---

_pages/omnia-gh.yaml

Add omnia-gh etc  file

---

_pages/red321123.yaml

Add file with handle, pageurl and timestamp

Add red321123.yaml

---

_pages/bmay1.yaml

Add bmay1's file

---

_pages/dav7824.yaml

zzzzzzzzzzzzzz

---

_pages/Phosisthedolphin.yaml

Added the .yaml file to the _yaml directory with my user name.

Added user info to Phosisthdolphin.yaml

---

_pages/MJLA77.yaml

---
githubHandle: YOUR-USERNAME
pageUrl: YOUR-HANDLE.github.io
timestamp: TODAYS-DATE-YYYY-MM-DD
---

adding githubhandle page url timestamp

---

_pages/figtree10.yaml

Reverts githubschool/on-demand-github-pages#3719

Revert "Name, website, date"

---

_pages/J-Chris-Garcia.yaml

output from CI tests.
Checking 1 external link...
- 
*  External link J-Chris-Garcia.github.io failed: 404 No error

website does not exist

---

_pages/scottone.yaml

What do u think @githubteacher ?

add _pages\scottone.yaml

---

_pagesirisyang123.yaml

add the file

---

_pages/anmonimill.yaml

added yaml file w/ handle, url and date

added yaml

---

_pages/RRFGamer.yaml
_pages/llshao.yaml

llshao-add-page
